### ISSUE TITLE
don't leave big comments of code

### ISSUE THREAD

**Issue by langdon** [BU-Spark/se-les-sons#15]
You shouldn't leave code in files without a lot of explanation. If you are afraid you might lose it, remember, that's what git is for. If it makes it out of your hands the next person (or future-you) may get confused as to why it is commented out.

https://github.com/BU-Spark/se-les-sons/blob/7377247bc2817b5bcd605e70199949589b1c199d/lib/Table_of_Contents.dart#L12

**Comment by tsmuskin** [comment]
Removed useless comments
